### PR TITLE
Add condensed format

### PR DESCRIPTION
**Pull request by parkr**
Add a new condensed format:

Screen Shot 2013-03-06 at 9 59 16 PM

It appears there is some really weird wrap issue that I couldn't fix. :/ Let me know what you think!!

### CODE REVIEW

**Comment by klaut** [comment]
Cool, thanks :thumbsup: ! 
Will have a look at it :) and if everything's fine I'll merge it in.

**Comment by parkr** [comment]
Sounds great! Let me know if you would like to see anything done differently and if you know how to fix the weird word-wrap error.

**Comment by klaut** [comment]
Hey, sorry for taking so long for this. I'll definitely do some work on it over this weekend. I did manage to fix the word-wrap error. Now Im trying to refactor the formatters as we have now three of them and they all have some duplicated code. Thanks again for your contribution :)

**Comment by parkr** [comment]
:)

**Pull request closed without merging**
